<template><div class="home"><section class="promo"><div><p class="eyebrow">SMART COMMERCE / REAL DATA</p><h1>好物精选，智能决策</h1><p>真实库存 · 用户评价 · AI 导购，让每次选择都有依据</p></div><el-button @click="$router.push('/ai-guide')">让 AI 帮我选 →</el-button></section><div class="categories"><button v-for="(category,i) in categoryNav" :key="category.id ?? category.name" :class="{active:i===0 && !selectedCategory}" @click="selectCategory(category)">{{ category.name }}</button></div><div class="search"><el-input v-model="keyword" placeholder="搜索商品名称、卖点或标签" @keyup.enter="search"><template #prefix>⌕</template></el-input><el-button type="primary" @click="search">搜索</el-button></div><h2 class="section-title">热门推荐</h2><el-alert v-if="loadError" title="首页数据加载失败，请重试" type="warning" show-icon :closable="false"><template #default><el-button link type="primary" @click="load">重新加载</el-button></template></el-alert><el-row :gutter="18"><el-col :xs="24" :sm="12" :lg="6" v-for="p in products" :key="p.id"><article class="product-card" @click="$router.push('/product/' + p.id)"><el-image :src="p.mainImage" fit="cover" class="product-image"><template #error><div class="image-error">暂无图片</div></template></el-image><div class="product-body"><div><el-tag size="small" type="success">推荐</el-tag><el-tag size="small">{{ p.categoryName || '精选商品' }}</el-tag></div><h3>{{ p.name }}</h3><p>{{ p.subtitle || '精选品质商品，满足你的日常需求' }}</p><div class="price">¥{{ p.price }}</div></div></article></el-col></el-row></div></template>
<script setup>
import { computed, ref, onMounted } from 'vue';import { useRouter } from 'vue-router';import request from '../../api/request'
const router=useRouter();const products=ref([]);const categories=ref([]);const keyword=ref('');const selectedCategory=ref(null);const loadError=ref(false);const fallbackCategories=['编程开发','运动鞋服','护肤套装','清洁电器','手机通讯','考试考证','健身装备','个护清洁','厨房电器','笔记本电脑','耳机音箱','智能穿戴']
const categoryNav=computed(()=>categories.value.length?[{id:null,name:'全部商品'},...categories.value.filter(c=>!c.parentId||c.parentId===0)]:[{id:null,name:'全部商品'},...fallbackCategories.map(name=>({id:null,name}))])
async function load(){loadError.value=false;try{const [hot,categoryData]=await Promise.all([request.get('/product/hot',{params:{limit:8}}),request.get('/category')]);products.value=Array.isArray(hot)?hot:[];categories.value=Array.isArray(categoryData)?categoryData:[]}catch{loadError.value=true;products.value=[];categories.value=[]}}
function selectCategory(category){selectedCategory.value=category.id;const query={};if(category.id)query.categoryId=String(category.id);else if(category.name&&category.name!=='全部商品')query.keyword=category.name;router.push({path:'/products',query})}
function search(){const query={};if(keyword.value.trim())query.keyword=keyword.value.trim();router.push({path:'/products',query})}onMounted(load)
</script>
<style scoped>
.home{max-width:1420px;margin:auto}.promo{position:relative;overflow:hidden;background:var(--tech);color:white;border-radius:8px;padding:42px 44px;display:flex;justify-content:space-between;align-items:center;border:1px solid #303640}.promo:after{content:'';position:absolute;right:-70px;bottom:-100px;width:280px;height:180px;border:36px solid rgba(242,85,61,.18);transform:rotate(-12deg)}.promo>div,.promo .el-button{position:relative;z-index:1}.promo .eyebrow{margin:0 0 12px;color:#ff8876;font-size:11px;font-weight:800;letter-spacing:2px}.promo h1{font-size:32px;margin:0 0 10px}.promo p{margin:0;color:#bec3ca}.promo .el-button{color:#fff;background:var(--brand);border:0;font-weight:700;height:42px}.categories{display:flex;flex-wrap:wrap;gap:6px;background:#fff;border:1px solid var(--line);border-radius:8px;padding:16px 18px;margin-top:18px}.categories button{border:0;background:transparent;padding:9px 14px;color:#5e6670;cursor:pointer;border-radius:6px;font-size:14px}.categories button:hover{color:var(--brand);background:var(--brand-soft)}.categories button.active{background:var(--brand);color:#fff}.search{display:flex;gap:14px;background:#fff;border:1px solid var(--line);border-radius:8px;padding:20px;margin-top:14px}.search .el-input{flex:1}.section-title{font-size:22px;margin:28px 0 16px;color:var(--ink)}.product-card{background:#fff;border:1px solid var(--line);border-radius:8px;overflow:hidden;cursor:pointer;transition:.2s}.product-card:hover{transform:translateY(-3px);border-color:var(--brand-border);box-shadow:0 12px 26px rgba(44,35,32,.09)}.product-image{width:100%;height:230px;display:block}.image-error{height:100%;display:grid;place-items:center;background:#f1f2f4;color:#9a9fa7}.product-body{padding:14px 16px}.product-body .el-tag{margin-right:6px}.product-body h3{font-size:17px;margin:12px 0 8px;color:var(--ink);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product-body p{height:42px;color:var(--muted);margin:0;font-size:13px;line-height:1.6}.price{color:var(--brand);font-size:23px;font-weight:800;margin-top:14px}@media(max-width:650px){.promo{align-items:flex-start;flex-direction:column;gap:24px;padding:30px 24px}.promo h1{font-size:27px}.promo .el-button{width:100%}.search{padding:14px}.section-title{margin-top:22px}}
</style>
