<template><div class="home"><section class="promo"><div><h1>好物精选，正品保障</h1><p>全场包邮 · 七天无理由退换 · 余额支付立减</p></div><el-button @click="$router.push('/ai-guide')">挑花眼？让 AI 帮我选 →</el-button></section><div class="categories"><button v-for="(category,i) in categoryNav" :key="category.id ?? category.name" :class="{active:i===0 && !selectedCategory}" @click="selectCategory(category)">{{ category.name }}</button></div><div class="search"><el-input v-model="keyword" placeholder="搜索商品名称、卖点或标签" @keyup.enter="search"><template #prefix>⌕</template></el-input><el-button type="primary" @click="search">搜索</el-button></div><h2 class="section-title">热门推荐</h2><el-row :gutter="18"><el-col :xs="24" :sm="12" :lg="6" v-for="p in products" :key="p.id"><article class="product-card" @click="$router.push('/product/' + p.id)"><el-image :src="p.mainImage" fit="cover" class="product-image" /><div class="product-body"><div><el-tag size="small" type="success">推荐</el-tag><el-tag size="small">{{ p.categoryName || '精选商品' }}</el-tag></div><h3>{{ p.name }}</h3><p>{{ p.subtitle || '精选品质商品，满足你的日常需求' }}</p><div class="price">¥{{ p.price }}</div></div></article></el-col></el-row></div></template>
<script setup>
import { computed, ref, onMounted } from 'vue';import { useRouter } from 'vue-router';import request from '../../api/request'
const router=useRouter();const products=ref([]);const categories=ref([]);const keyword=ref('');const selectedCategory=ref(null);const fallbackCategories=['编程开发','运动鞋服','护肤套装','清洁电器','手机通讯','考试考证','健身装备','个护清洁','厨房电器','笔记本电脑','耳机音箱','智能穿戴']
const categoryNav=computed(()=>categories.value.length?[{id:null,name:'全部商品'},...categories.value.filter(c=>!c.parentId||c.parentId===0)]:[{id:null,name:'全部商品'},...fallbackCategories.map(name=>({id:null,name}))])
async function load(){const [hot,categoryData]=await Promise.all([request.get('/product/hot',{params:{limit:8}}),request.get('/category')]);products.value=hot;categories.value=categoryData||[]}function selectCategory(category){selectedCategory.value=category.id;const query={};if(category.id)query.categoryId=String(category.id);router.push({path:'/products',query})}function search(){const query={};if(keyword.value.trim())query.keyword=keyword.value.trim();router.push({path:'/products',query})}onMounted(load)
</script>
<style scoped>
.home{max-width:1420px;margin:auto}.promo{background:linear-gradient(110deg,#ff665d,#ff956b);color:white;border-radius:10px;padding:38px 44px;display:flex;justify-content:space-between;align-items:center}.promo h1{font-size:32px;margin:0 0 10px}.promo p{margin:0;opacity:.9}.promo .el-button{color:#ff665d;border:0;font-weight:700}.categories{display:flex;flex-wrap:wrap;gap:6px;background:#fff;border:1px solid #e3ebef;border-radius:10px;padding:16px 18px;margin-top:18px}.categories button{border:0;background:transparent;padding:9px 14px;color:#53697b;cursor:pointer;border-radius:20px;font-size:14px}.categories button.active{background:#ff665d;color:#fff}.search{display:flex;gap:14px;background:#fff;border:1px solid #e3ebef;border-radius:10px;padding:20px;margin-top:14px}.search .el-input{flex:1}.section-title{font-size:22px;margin:28px 0 16px}.product-card{background:#fff;border:1px solid #e2ebf0;border-radius:10px;overflow:hidden;cursor:pointer;transition:.2s}.product-card:hover{transform:translateY(-3px);box-shadow:0 10px 24px rgba(34,75,100,.1)}.product-image{width:100%;height:230px;display:block}.product-body{padding:14px 16px}.product-body .el-tag{margin-right:6px}.product-body h3{font-size:17px;margin:12px 0 8px;color:#1e2e3d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product-body p{height:42px;color:#778b9a;margin:0;font-size:13px;line-height:1.6}.price{color:#ff5c4f;font-size:23px;font-weight:800;margin-top:14px}
</style>
