<template>
  <div v-if="product" class="detail-page">
    <section class="product-overview"><div class="gallery"><el-image :src="activeImage" fit="cover" class="main-image" /><div class="thumbs"><button v-for="(image, i) in gallery" :key="image" :class="{ selected: activeIndex === i }" @click="activeIndex = i"><el-image :src="image" fit="cover" /></button></div></div><div class="product-info"><h1>{{ product.name }}</h1><p class="subtitle">{{ product.subtitle }}</p><div class="price-box"><strong>¥{{ product.price }}</strong><del v-if="product.originalPrice">¥{{ product.originalPrice }}</del></div><div class="meta"><span>商品编号：SP{{ String(product.id).padStart(12, '0') }}</span><span>库存：<b>{{ product.stock }} 件</b></span></div><div class="purchase"><el-input-number v-model="quantity" :min="1" :max="Math.max(product.stock || 1, 1)" /><el-button @click="favorite">收藏</el-button><el-button type="primary" @click="addCart">加入购物车</el-button></div></div></section>
    <section class="detail-panel"><el-tabs v-model="activeTab"><el-tab-pane label="商品详情" name="detail"><div class="rich-detail" v-html="product.detailHtml || '<p>暂无详情描述</p>'"></div></el-tab-pane><el-tab-pane :label="`规格参数(${paramCount})`" name="params"><div class="params"><div v-for="(value, key) in parsedParams" :key="key"><span>{{ key }}</span><b>{{ value }}</b></div><el-empty v-if="!Object.keys(parsedParams).length" description="暂无规格参数" /></div></el-tab-pane><el-tab-pane :label="`用户评价(${reviews.length})`" name="reviews"><div v-if="reviews.length" class="reviews"><article v-for="r in reviews" :key="r.id"><div class="review-head"><b>{{ r.nickname || r.username || '匿名用户' }}</b><el-rate :model-value="r.rating" disabled /></div><p>{{ r.content }}</p><small>{{ r.createTime }}</small></article></div><el-empty v-else description="暂无评价" /></el-tab-pane><el-tab-pane label="AI 问答" name="qa"><div class="qa-intro">AI 会结合当前商品资料和实时价格、库存回答你的问题，并支持连续追问。</div><div class="question-row"><el-input v-model="question" type="textarea" :rows="3" placeholder="例如：这个商品适合什么场景使用？" /><el-button type="primary" :loading="qaLoading" @click="ask">提问</el-button></div><div v-if="qaMessages.length" class="qa-history"><div v-for="(message, index) in qaMessages" :key="index" :class="['qa-message', message.role]"><b>{{ message.role === 'user' ? '我' : 'AI' }}</b><p>{{ message.content }}</p></div></div></el-tab-pane></el-tabs></section>
  </div><el-empty v-else :description="loadError ? '商品详情加载失败' : '正在加载商品详情...'" ><template #default><el-button v-if="loadError" type="primary" plain @click="load">重新加载</el-button></template></el-empty>
</template>
<script setup>
import { ref, computed, onMounted, watch } from 'vue'; import { useRoute } from 'vue-router'; import { ElMessage } from 'element-plus'; import request from '../../api/request'
const route=useRoute();const product=ref(null);const images=ref([]);const reviews=ref([]);const quantity=ref(1);const activeIndex=ref(0);const activeTab=ref('detail');const question=ref('');const qaLoading=ref(false);const qaMessages=ref([]);const loading=ref(false);const loadError=ref(false)
const gallery=computed(()=>{const list=images.value.map(i=>i.url).filter(Boolean);return [...new Set([product.value?.mainImage,...list].filter(Boolean))]});const activeImage=computed(()=>gallery.value[activeIndex.value]||product.value?.mainImage);const parsedParams=computed(()=>{try{return typeof product.value?.paramsJson==='string'?JSON.parse(product.value.paramsJson||'{}'):(product.value?.paramsJson||{})}catch{return {}}});const paramCount=computed(()=>Object.keys(parsedParams.value).length)
async function load(){loading.value=true;loadError.value=false;try{const data=await request.get(`/product/${route.params.id}`);product.value=data.product;images.value=data.images||[];try{reviews.value=await request.get(`/review/product/${route.params.id}`)}catch{reviews.value=[];ElMessage.warning('商品评价暂时加载失败')} }catch{product.value=null;loadError.value=true}finally{loading.value=false}}
async function addCart(){if(!product.value||product.value.stock<=0)return ElMessage.warning('商品暂时缺货');await request.post('/cart',{productId:product.value.id,quantity:quantity.value});ElMessage.success('已加入购物车')}
async function favorite(){await request.post('/favorite',{productId:product.value.id});ElMessage.success('已收藏')}
async function ask(){if(!question.value.trim())return ElMessage.warning('请输入问题');const current=question.value.trim();const history=qaMessages.value.slice(-10).map(({role,content})=>({role,content}));qaMessages.value.push({role:'user',content:current});question.value='';qaLoading.value=true;try{const data=await request.post('/ai/chat',{question:current,history,questionType:'PRODUCT_KNOWLEDGE',productId:product.value.id});qaMessages.value.push({role:'assistant',content:data.answer||'暂无回答'})}catch{qaMessages.value.pop()}finally{qaLoading.value=false}}
watch(gallery, value => { if (activeIndex.value >= value.length) activeIndex.value = 0 })
onMounted(load)
</script>
<style scoped>
.detail-page{max-width:1380px;margin:auto}.product-overview,.detail-panel{background:#fff;border:1px solid var(--line);border-radius:8px}.product-overview{display:grid;grid-template-columns:480px 1fr;gap:34px;padding:28px}.gallery{min-width:0}.main-image{width:100%;height:410px;border-radius:8px;background:#f4f6f8}.thumbs{display:flex;gap:10px;margin-top:14px}.thumbs button{padding:0;border:2px solid transparent;border-radius:8px;background:#fff;cursor:pointer}.thumbs button.selected{border-color:var(--brand)}.thumbs .el-image{width:72px;height:62px;border-radius:7px}.product-info{padding:5px 18px}.product-info h1{font-size:28px;margin:0 0 10px;color:var(--ink)}.subtitle{color:#7f929e;font-size:15px}.price-box{display:flex;align-items:baseline;gap:12px;background:var(--brand-soft);border-radius:8px;padding:20px;margin-top:28px}.price-box strong{font-size:38px;color:var(--brand)}.price-box del{color:#aab6bd}.meta{display:flex;gap:36px;color:#7b909d;margin:24px 0}.meta b{color:#45a34b}.purchase{display:flex;align-items:center;gap:12px}.purchase .el-button{height:42px}.detail-panel{padding:20px 28px;margin-top:18px}.rich-detail{line-height:1.9;color:#475e6d}.params{max-width:720px}.params>div{display:grid;grid-template-columns:180px 1fr;padding:14px;border-bottom:1px solid #edf1f3}.params span{color:#8295a1}.reviews article{padding:16px 0;border-bottom:1px solid #edf1f3}.review-head{display:flex;gap:14px;align-items:center}.reviews p{color:#536c7a}.reviews small{color:#a5b2ba}.qa-intro{padding:14px;border-left:3px solid var(--ai-cyan);background:#f3fafb;color:#657982;line-height:1.7}.question-row{display:flex;gap:12px;margin-top:16px}.question-row .el-input{flex:1}.qa-history{max-height:420px;overflow:auto;margin-top:16px}.qa-message{display:flex;gap:10px;align-items:flex-start;margin:10px 0}.qa-message b{display:grid;place-items:center;flex:none;width:28px;height:28px;border-radius:6px;background:#daf4f6;color:#168da5;font-size:11px}.qa-message p{max-width:88%;margin:0;padding:10px 13px;border-radius:8px;background:#f1f5f7;color:#456370;line-height:1.7;white-space:pre-wrap}.qa-message.user{justify-content:flex-end}.qa-message.user b{order:2;background:var(--brand);color:#fff}.qa-message.user p{order:1;background:var(--brand-soft);color:#704239}@media(max-width:800px){.product-overview{grid-template-columns:1fr;padding:18px}.main-image{height:300px}.product-info{padding:0}.product-info h1{font-size:22px}.price-box strong{font-size:30px}.question-row{flex-direction:column}}
</style>
