<template><div class="auth-page"><div class="auth-shell"><section class="auth-visual"><div class="visual-brand"><span class="logo-mark">AI</span><span><b>智选商城</b><small>AI SHOPPING ASSISTANT</small></span></div><div class="visual-copy"><p class="eyebrow">● 你的专属智能导购</p><h1>不只是搜索商品<br><em>更懂你的每次选择</em></h1><p>说出需求，AI 将结合预算、偏好、库存和真实评价，为你筛选更合适的商品。</p><div class="demo-card"><div class="demo-head">为你精选 3 款高匹配商品<span>预算 800 元，想买一款通勤降噪耳机</span></div><div class="demo-row"><b>降噪</b><strong>AirSound Pro</strong><span>¥699</span></div><div class="demo-row"><b class="purple">轻盈</b><strong>CloudBuds 3</strong><span>¥529</span></div></div></div><div class="visual-foot">✓ 个性推荐　 ✓ 智能比价　 ✓ 售前售后问答</div></section><section class="auth-card"><p class="welcome">WELCOME BACK</p><h2>登录智选商城</h2><p class="sub">开启更高效、更懂你的智能购物体验</p><el-form :model="form" @submit.prevent="login"><label>账号</label><el-form-item><el-input v-model="form.username" placeholder="请输入商城账号" /></el-form-item><label>密码</label><el-form-item><el-input v-model="form.password" type="password" placeholder="请输入登录密码" show-password /></el-form-item><el-button class="enter-btn" type="primary" :loading="loading" @click="login">进入商城 →</el-button><div class="divider"><span>新用户</span></div><div class="auth-links">还没有商城账号？ <router-link to="/register">立即注册</router-link></div><p class="secure">● 账号信息已加密保护，请放心登录</p></el-form></section></div></div></template>
<script setup>
import { ref } from 'vue'; import { useRouter } from 'vue-router'; import request from '../api/request'; import { useUserStore } from '../stores/user'; import { ElMessage } from 'element-plus'
const router=useRouter();const store=useUserStore();const form=ref({username:'',password:''});const loading=ref(false)
async function login(){loading.value=true;try{const data=await request.post('/auth/login',form.value);store.setLogin(data);form.value={username:'',password:''};ElMessage.success('登录成功');router.push(data.user?.role==='ADMIN'?'/admin':'/')}finally{loading.value=false}}
</script>
<style scoped>
.auth-page{min-height:100%;display:flex;align-items:center;justify-content:center;background:#eef0f3;padding:36px}.auth-shell{display:grid;grid-template-columns:1fr 1fr;width:min(1100px,100%);min-height:620px;border-radius:8px;overflow:hidden;box-shadow:0 24px 70px rgba(25,28,33,.16);background:#fff}.auth-visual{background:var(--tech);color:#fff;padding:42px 50px 34px;display:flex;flex-direction:column}.visual-brand{display:flex;align-items:center;gap:10px}.visual-brand b{display:block;font-size:18px}.visual-brand small{display:block;color:#9ca2ab;font-size:10px;letter-spacing:1.5px;margin-top:3px}.visual-copy{margin:auto 0;max-width:520px}.eyebrow{color:var(--ai-cyan);font-weight:700}.visual-copy h1{font-size:43px;line-height:1.18;margin:22px 0 16px}.visual-copy h1 em{color:#ff7864;font-style:normal}.visual-copy>p:not(.eyebrow){color:#bcc1c8;line-height:1.8}.demo-card{margin-top:28px;padding:18px;background:#232932;border:1px solid #383f49;border-radius:8px}.demo-head{font-size:14px;font-weight:700;margin-bottom:14px}.demo-head span{display:block;color:#aeb4bc;font-size:12px;font-weight:400;margin-top:8px}.demo-row{display:flex;align-items:center;gap:12px;padding:12px 10px;background:#1b2027;border-bottom:1px solid #353b44}.demo-row:last-child{border:0}.demo-row b{background:#714136;color:#ffb0a2;padding:8px 7px;border-radius:5px;font-size:11px}.demo-row b.purple{background:#245660;color:#83d7df}.demo-row strong{flex:1}.demo-row span{color:#f3f4f5;font-weight:700}.visual-foot{color:#989fa8;font-size:12px}.auth-card{padding:90px 58px}.welcome{color:var(--brand);font-size:12px;letter-spacing:2px;font-weight:800}.auth-card h2{font-size:32px;margin:18px 0 8px;color:var(--ink)}.sub{color:#949aa3;margin-bottom:34px}.auth-card label{display:block;font-weight:700;font-size:13px;margin:14px 0 8px}.auth-card :deep(.el-input__wrapper){min-height:52px;background:#f7f8f9;box-shadow:0 0 0 1px var(--line) inset;border-radius:7px}.enter-btn{width:100%;height:54px;font-size:16px;font-weight:700;margin-top:14px;border-radius:7px}.divider{display:flex;align-items:center;gap:10px;color:#bcc0c6;font-size:12px;margin:28px 0}.divider:before,.divider:after{content:'';flex:1;height:1px;background:var(--line)}.auth-links{text-align:center;color:#8b929b}.auth-links a{color:var(--brand);font-weight:700;text-decoration:none}.secure{text-align:center;color:#aeb3ba;font-size:12px;margin-top:32px}.logo-mark{width:38px;height:38px;display:grid;place-items:center;border-radius:7px;background:var(--brand);color:#fff;font-weight:800;box-shadow:0 0 0 4px rgba(242,85,61,.16)}@media(max-width:760px){.auth-page{padding:0}.auth-shell{grid-template-columns:1fr;border-radius:0}.auth-visual{min-height:350px;padding:28px}.visual-copy h1{font-size:31px}.demo-card{display:none}.auth-card{padding:42px 28px}}
</style>
